server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    # SPA-reititys: kaikki tuntemattomat polut palauttavat index.html
    location / {
        try_files $uri /index.html;
    }
}